"use client";

import Link from "next/link";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  Button,
  Badge,
  DataTable,
  StatCard,
} from "@cliniq/ui";
import {
  Users,
  Mic,
  PhoneIncoming,
  AlertTriangle,
  FileText,
  ArrowRight,
} from "lucide-react";

interface WorklistItem {
  id: string;
  name: string;
  mrn: string;
  dob: string;
  employer: string;
  riskTier: "low" | "moderate" | "high";
  gapCount: number;
  lastVisit: string;
  status: string;
  [key: string]: string | number;
}

const DEMO_WORKLIST: WorklistItem[] = [
  { id: "p-1", name: "Sarah Johnson", mrn: "948204", dob: "1988-04-12", employer: "Apex Global Tech", riskTier: "low", gapCount: 1, lastVisit: "Aug 15, 2026", status: "Active Verified" },
  { id: "p-2", name: "Marcus Miller", mrn: "830219", dob: "1972-11-03", employer: "Apex Global Tech", riskTier: "high", gapCount: 3, lastVisit: "Jul 29, 2026", status: "Pending Triage" },
  { id: "p-3", name: "David Vance", mrn: "419820", dob: "1965-06-21", employer: "Summit Health Logistics", riskTier: "moderate", gapCount: 2, lastVisit: "Aug 02, 2026", status: "Active Verified" },
  { id: "p-4", name: "Emily Watson", mrn: "550192", dob: "1994-09-18", employer: "Apex Global Tech", riskTier: "low", gapCount: 0, lastVisit: "Aug 20, 2026", status: "Active Verified" },
];

export default function ProviderDashboard() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between border-b border-[var(--line)] pb-6">
        <div>
          <div className="flex items-center gap-2 font-mono text-xs text-[var(--ink-muted)] mb-1">
            <span className="size-1.5 rounded-full bg-emerald-500" />
            <span>CLINICIAN_STATION // NURSE_ER_PANEL</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-medium tracking-tight text-[var(--ink)]">
            Clinical Triage & Worklist
          </h1>
          <p className="font-mono text-xs text-[var(--ink-muted)] mt-1">
            Real-time patient panel invariant queue, ambient SOAP generation sessions, and incoming care dispatches.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Link href="/provider/scribe">
            <Button size="sm" className="font-mono text-xs gap-2">
              <Mic className="size-3.5" /> Launch Ambient Scribe
            </Button>
          </Link>
        </div>
      </div>

      {/* Metric Stat Cards */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <StatCard
          title="Assigned Cohort"
          value="48 Active"
          subtitle="4 High Risk Invariant Violations"
          icon={<Users className="size-4 text-sky-400" />}
          loincCode="PANEL: NURSE-PRIMARY"
        />
        <StatCard
          title="Triage Queue"
          value="2 Pending"
          subtitle="Avg queue latency: 4m 12s"
          trend="down"
          icon={<PhoneIncoming className="size-4 text-amber-500" />}
          loincCode="DISPATCH: PRIORITY-1"
        />
        <StatCard
          title="Unclosed Gaps"
          value="14 Gaps"
          subtitle="6 Retinal · 8 HbA1c Monitored"
          icon={<AlertTriangle className="size-4 text-rose-500" />}
          loincCode="HEDIS: PANEL-AGGREGATE"
        />
        <StatCard
          title="Draft SOAP Attestations"
          value="3 Ready"
          subtitle="Generated by Anthropic Claude 3.5"
          icon={<FileText className="size-4 text-emerald-500" />}
          loincCode="FHIR: COMPOSITION-DRAFT"
        />
      </div>

      {/* Patient Worklist Table */}
      <Card notch className="bg-[var(--paper-raised)]">
        <CardHeader className="pb-3 border-b border-[var(--line)] bg-[var(--paper-sunken)]">
          <div className="flex items-center justify-between">
            <CardTitle className="text-sm font-mono font-semibold uppercase tracking-wider">Assigned Patient Panel</CardTitle>
            <span className="text-[10px] text-[var(--ink-faint)] font-mono">ORG: NUVI HEALTH CORE</span>
          </div>
          <CardDescription className="font-mono text-xs">
            Directly open patient longitudinal FHIR charts to inspect vitals, dispense orders, and review AI notes.
          </CardDescription>
        </CardHeader>
        <CardContent className="pt-4">
          <DataTable<WorklistItem>
            data={DEMO_WORKLIST}
            keyExtractor={(item) => item.id}
            searchPlaceholder="Search patients by name, MRN, or employer group..."
            searchFilter={(item, q) =>
              item.name.toLowerCase().includes(q) ||
              item.mrn.includes(q) ||
              item.employer.toLowerCase().includes(q)
            }
            columns={[
              {
                key: "name",
                header: "Patient Identifier",
                render: (item) => (
                  <div>
                    <span className="font-semibold text-[var(--ink)]">{item.name}</span>
                    <p className="font-mono text-[10px] text-[var(--ink-faint)] mt-0.5">MRN: {item.mrn} · DOB: {item.dob}</p>
                  </div>
                ),
              },
              { key: "employer", header: "Employer Group" },
              {
                key: "riskTier",
                header: "Risk Tier",
                render: (item) => (
                  <Badge
                    variant={
                      item.riskTier === "high"
                        ? "destructive"
                        : item.riskTier === "moderate"
                        ? "warning"
                        : "success"
                    }
                    dot
                  >
                    {item.riskTier.toUpperCase()}
                  </Badge>
                ),
              },
              {
                key: "gapCount",
                header: "Open Care Gaps",
                render: (item) => (
                  <span className={item.gapCount > 0 ? "font-mono font-semibold text-amber-400" : "font-mono text-[var(--ink-faint)]"}>
                    {item.gapCount} open
                  </span>
                ),
              },
              {
                key: "status",
                header: "Triage State",
                render: (item) => (
                  <Badge variant={item.status.includes("Pending") ? "warning" : "secondary"}>
                    {item.status}
                  </Badge>
                ),
              },
              {
                key: "actions",
                header: "Action",
                render: (item) => (
                  <Link href={`/provider/chart/${item.id}`}>
                    <Button size="sm" variant="outline" className="font-mono text-xs">
                      Open Chart <ArrowRight className="size-3 ml-1" />
                    </Button>
                  </Link>
                ),
              },
            ]}
          />
        </CardContent>
      </Card>
    </div>
  );
}


